### ISSUE TITLE
ImmutableParser does not support class java.time.LocalDateTime

### ISSUE THREAD

**Issue by flyaruu** [floodplainio/floodplain-library#5]
See:

```
java.lang.IllegalArgumentException: Unknown type: class java.time.LocalDateTime
	at io.floodplain.immutable.factory.ImmutableFactory.resolveTypeFromValue(ImmutableFactory.java:89)
	at io.floodplain.kotlindsl.message.IMessageImpl.toImmutable(IMessage.kt:240)
	at io.floodplain.ApplicationKt$output$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:133)
	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:96)
	at kotlinx.coroutines.reactive.PublisherAsFlow.collect(ReactiveFlow.kt:75)
```

**Comment by flyaruu** [comment]
Fixed, even though some sinks have issues with the new Java Time classes
